
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
namespace ThemifyIcons.WPF
{
	///<summary>
	///	Themify Icons 0.1.2 by lykmapipo (@lallyelias87@gmail.com), themify.me (@http://themify.me/themify-icons)
	///	icons,line,iOS,pixel,perfect,draw
	///	License https://github.com/lykmapipo/themify-icons/blob/master/README.md (Font: 0.1.2, C#: MIT,OFL License)
	///</summary>
	///<see href="https://github.com/lykmapipo/themify-icons" />
	///<seealso href="https://github.com/alexandrelugand/Themify-Icons-WPF" />
	public enum ThemifyIconsIcon
	{
		///<summary>Set this value to show no icon.</summary>
		None = 0x0,
		///<summary>Wand</summary>
		[Description("Wand"),IconId("wand"),IconCategory("Themify Icons")]
		Wand = 0xe600,
		///<summary>Volume</summary>
		[Description("Volume"),IconId("volume"),IconCategory("Themify Icons")]
		Volume = 0xe601,
		///<summary>User</summary>
		[Description("User"),IconId("user"),IconCategory("Themify Icons")]
		User = 0xe602,
		///<summary>Unlock</summary>
		[Description("Unlock"),IconId("unlock"),IconCategory("Themify Icons")]
		Unlock = 0xe603,
		///<summary>Unlink</summary>
		[Description("Unlink"),IconId("unlink"),IconCategory("Themify Icons")]
		Unlink = 0xe604,
		///<summary>Trash</summary>
		[Description("Trash"),IconId("trash"),IconCategory("Themify Icons")]
		Trash = 0xe605,
		///<summary>Thought</summary>
		[Description("Thought"),IconId("thought"),IconCategory("Themify Icons")]
		Thought = 0xe606,
		///<summary>Target</summary>
		[Description("Target"),IconId("target"),IconCategory("Themify Icons")]
		Target = 0xe607,
		///<summary>Tag</summary>
		[Description("Tag"),IconId("tag"),IconCategory("Themify Icons")]
		Tag = 0xe608,
		///<summary>Tablet</summary>
		[Description("Tablet"),IconId("tablet"),IconCategory("Themify Icons")]
		Tablet = 0xe609,
		///<summary>Star</summary>
		[Description("Star"),IconId("star"),IconCategory("Themify Icons")]
		Star = 0xe60a,
		///<summary>Spray</summary>
		[Description("Spray"),IconId("spray"),IconCategory("Themify Icons")]
		Spray = 0xe60b,
		///<summary>Signal</summary>
		[Description("Signal"),IconId("signal"),IconCategory("Themify Icons")]
		Signal = 0xe60c,
		///<summary>ShoppingCart</summary>
		[Description("ShoppingCart"),IconId("shopping-cart"),IconCategory("Themify Icons")]
		ShoppingCart = 0xe60d,
		///<summary>ShoppingCartFull</summary>
		[Description("ShoppingCartFull"),IconId("shopping-cart-full"),IconCategory("Themify Icons")]
		ShoppingCartFull = 0xe60e,
		///<summary>Settings</summary>
		[Description("Settings"),IconId("settings"),IconCategory("Themify Icons")]
		Settings = 0xe60f,
		///<summary>Search</summary>
		[Description("Search"),IconId("search"),IconCategory("Themify Icons")]
		Search = 0xe610,
		///<summary>ZoomIn</summary>
		[Description("ZoomIn"),IconId("zoom-in"),IconCategory("Themify Icons")]
		ZoomIn = 0xe611,
		///<summary>ZoomOut</summary>
		[Description("ZoomOut"),IconId("zoom-out"),IconCategory("Themify Icons")]
		ZoomOut = 0xe612,
		///<summary>Cut</summary>
		[Description("Cut"),IconId("cut"),IconCategory("Themify Icons")]
		Cut = 0xe613,
		///<summary>Ruler</summary>
		[Description("Ruler"),IconId("ruler"),IconCategory("Themify Icons")]
		Ruler = 0xe614,
		///<summary>RulerPencil</summary>
		[Description("RulerPencil"),IconId("ruler-pencil"),IconCategory("Themify Icons")]
		RulerPencil = 0xe615,
		///<summary>RulerAlt</summary>
		[Description("RulerAlt"),IconId("ruler-alt"),IconCategory("Themify Icons")]
		RulerAlt = 0xe616,
		///<summary>Bookmark</summary>
		[Description("Bookmark"),IconId("bookmark"),IconCategory("Themify Icons")]
		Bookmark = 0xe617,
		///<summary>BookmarkAlt</summary>
		[Description("BookmarkAlt"),IconId("bookmark-alt"),IconCategory("Themify Icons")]
		BookmarkAlt = 0xe618,
		///<summary>Reload</summary>
		[Description("Reload"),IconId("reload"),IconCategory("Themify Icons")]
		Reload = 0xe619,
		///<summary>Plus</summary>
		[Description("Plus"),IconId("plus"),IconCategory("Themify Icons")]
		Plus = 0xe61a,
		///<summary>Pin</summary>
		[Description("Pin"),IconId("pin"),IconCategory("Themify Icons")]
		Pin = 0xe61b,
		///<summary>Pencil</summary>
		[Description("Pencil"),IconId("pencil"),IconCategory("Themify Icons")]
		Pencil = 0xe61c,
		///<summary>PencilAlt</summary>
		[Description("PencilAlt"),IconId("pencil-alt"),IconCategory("Themify Icons")]
		PencilAlt = 0xe61d,
		///<summary>PaintRoller</summary>
		[Description("PaintRoller"),IconId("paint-roller"),IconCategory("Themify Icons")]
		PaintRoller = 0xe61e,
		///<summary>PaintBucket</summary>
		[Description("PaintBucket"),IconId("paint-bucket"),IconCategory("Themify Icons")]
		PaintBucket = 0xe61f,
		///<summary>Na</summary>
		[Description("Na"),IconId("na"),IconCategory("Themify Icons")]
		Na = 0xe620,
		///<summary>Mobile</summary>
		[Description("Mobile"),IconId("mobile"),IconCategory("Themify Icons")]
		Mobile = 0xe621,
		///<summary>Minus</summary>
		[Description("Minus"),IconId("minus"),IconCategory("Themify Icons")]
		Minus = 0xe622,
		///<summary>Medall</summary>
		[Description("Medall"),IconId("medall"),IconCategory("Themify Icons")]
		Medall = 0xe623,
		///<summary>MedallAlt</summary>
		[Description("MedallAlt"),IconId("medall-alt"),IconCategory("Themify Icons")]
		MedallAlt = 0xe624,
		///<summary>Marker</summary>
		[Description("Marker"),IconId("marker"),IconCategory("Themify Icons")]
		Marker = 0xe625,
		///<summary>MarkerAlt</summary>
		[Description("MarkerAlt"),IconId("marker-alt"),IconCategory("Themify Icons")]
		MarkerAlt = 0xe626,
		///<summary>ArrowUp</summary>
		[Description("ArrowUp"),IconId("arrow-up"),IconCategory("Themify Icons")]
		ArrowUp = 0xe627,
		///<summary>ArrowRight</summary>
		[Description("ArrowRight"),IconId("arrow-right"),IconCategory("Themify Icons")]
		ArrowRight = 0xe628,
		///<summary>ArrowLeft</summary>
		[Description("ArrowLeft"),IconId("arrow-left"),IconCategory("Themify Icons")]
		ArrowLeft = 0xe629,
		///<summary>ArrowDown</summary>
		[Description("ArrowDown"),IconId("arrow-down"),IconCategory("Themify Icons")]
		ArrowDown = 0xe62a,
		///<summary>Lock</summary>
		[Description("Lock"),IconId("lock"),IconCategory("Themify Icons")]
		Lock = 0xe62b,
		///<summary>LocationArrow</summary>
		[Description("LocationArrow"),IconId("location-arrow"),IconCategory("Themify Icons")]
		LocationArrow = 0xe62c,
		///<summary>Link</summary>
		[Description("Link"),IconId("link"),IconCategory("Themify Icons")]
		Link = 0xe62d,
		///<summary>Layout</summary>
		[Description("Layout"),IconId("layout"),IconCategory("Themify Icons")]
		Layout = 0xe62e,
		///<summary>Layers</summary>
		[Description("Layers"),IconId("layers"),IconCategory("Themify Icons")]
		Layers = 0xe62f,
		///<summary>LayersAlt</summary>
		[Description("LayersAlt"),IconId("layers-alt"),IconCategory("Themify Icons")]
		LayersAlt = 0xe630,
		///<summary>Key</summary>
		[Description("Key"),IconId("key"),IconCategory("Themify Icons")]
		Key = 0xe631,
		///<summary>Import</summary>
		[Description("Import"),IconId("import"),IconCategory("Themify Icons")]
		Import = 0xe632,
		///<summary>Image</summary>
		[Description("Image"),IconId("image"),IconCategory("Themify Icons")]
		Image = 0xe633,
		///<summary>Heart</summary>
		[Description("Heart"),IconId("heart"),IconCategory("Themify Icons")]
		Heart = 0xe634,
		///<summary>HeartBroken</summary>
		[Description("HeartBroken"),IconId("heart-broken"),IconCategory("Themify Icons")]
		HeartBroken = 0xe635,
		///<summary>HandStop</summary>
		[Description("HandStop"),IconId("hand-stop"),IconCategory("Themify Icons")]
		HandStop = 0xe636,
		///<summary>HandOpen</summary>
		[Description("HandOpen"),IconId("hand-open"),IconCategory("Themify Icons")]
		HandOpen = 0xe637,
		///<summary>HandDrag</summary>
		[Description("HandDrag"),IconId("hand-drag"),IconCategory("Themify Icons")]
		HandDrag = 0xe638,
		///<summary>Folder</summary>
		[Description("Folder"),IconId("folder"),IconCategory("Themify Icons")]
		Folder = 0xe639,
		///<summary>Flag</summary>
		[Description("Flag"),IconId("flag"),IconCategory("Themify Icons")]
		Flag = 0xe63a,
		///<summary>FlagAlt</summary>
		[Description("FlagAlt"),IconId("flag-alt"),IconCategory("Themify Icons")]
		FlagAlt = 0xe63b,
		///<summary>FlagAlt2</summary>
		[Description("FlagAlt2"),IconId("flag-alt-2"),IconCategory("Themify Icons")]
		FlagAlt2 = 0xe63c,
		///<summary>Eye</summary>
		[Description("Eye"),IconId("eye"),IconCategory("Themify Icons")]
		Eye = 0xe63d,
		///<summary>Export</summary>
		[Description("Export"),IconId("export"),IconCategory("Themify Icons")]
		Export = 0xe63e,
		///<summary>ExchangeVertical</summary>
		[Description("ExchangeVertical"),IconId("exchange-vertical"),IconCategory("Themify Icons")]
		ExchangeVertical = 0xe63f,
		///<summary>Desktop</summary>
		[Description("Desktop"),IconId("desktop"),IconCategory("Themify Icons")]
		Desktop = 0xe640,
		///<summary>Cup</summary>
		[Description("Cup"),IconId("cup"),IconCategory("Themify Icons")]
		Cup = 0xe641,
		///<summary>Crown</summary>
		[Description("Crown"),IconId("crown"),IconCategory("Themify Icons")]
		Crown = 0xe642,
		///<summary>Comments</summary>
		[Description("Comments"),IconId("comments"),IconCategory("Themify Icons")]
		Comments = 0xe643,
		///<summary>Comment</summary>
		[Description("Comment"),IconId("comment"),IconCategory("Themify Icons")]
		Comment = 0xe644,
		///<summary>CommentAlt</summary>
		[Description("CommentAlt"),IconId("comment-alt"),IconCategory("Themify Icons")]
		CommentAlt = 0xe645,
		///<summary>Close</summary>
		[Description("Close"),IconId("close"),IconCategory("Themify Icons")]
		Close = 0xe646,
		///<summary>Clip</summary>
		[Description("Clip"),IconId("clip"),IconCategory("Themify Icons")]
		Clip = 0xe647,
		///<summary>AngleUp</summary>
		[Description("AngleUp"),IconId("angle-up"),IconCategory("Themify Icons")]
		AngleUp = 0xe648,
		///<summary>AngleRight</summary>
		[Description("AngleRight"),IconId("angle-right"),IconCategory("Themify Icons")]
		AngleRight = 0xe649,
		///<summary>AngleLeft</summary>
		[Description("AngleLeft"),IconId("angle-left"),IconCategory("Themify Icons")]
		AngleLeft = 0xe64a,
		///<summary>AngleDown</summary>
		[Description("AngleDown"),IconId("angle-down"),IconCategory("Themify Icons")]
		AngleDown = 0xe64b,
		///<summary>Check</summary>
		[Description("Check"),IconId("check"),IconCategory("Themify Icons")]
		Check = 0xe64c,
		///<summary>CheckBox</summary>
		[Description("CheckBox"),IconId("check-box"),IconCategory("Themify Icons")]
		CheckBox = 0xe64d,
		///<summary>Camera</summary>
		[Description("Camera"),IconId("camera"),IconCategory("Themify Icons")]
		Camera = 0xe64e,
		///<summary>Announcement</summary>
		[Description("Announcement"),IconId("announcement"),IconCategory("Themify Icons")]
		Announcement = 0xe64f,
		///<summary>Brush</summary>
		[Description("Brush"),IconId("brush"),IconCategory("Themify Icons")]
		Brush = 0xe650,
		///<summary>Briefcase</summary>
		[Description("Briefcase"),IconId("briefcase"),IconCategory("Themify Icons")]
		Briefcase = 0xe651,
		///<summary>Bolt</summary>
		[Description("Bolt"),IconId("bolt"),IconCategory("Themify Icons")]
		Bolt = 0xe652,
		///<summary>BoltAlt</summary>
		[Description("BoltAlt"),IconId("bolt-alt"),IconCategory("Themify Icons")]
		BoltAlt = 0xe653,
		///<summary>Blackboard</summary>
		[Description("Blackboard"),IconId("blackboard"),IconCategory("Themify Icons")]
		Blackboard = 0xe654,
		///<summary>Bag</summary>
		[Description("Bag"),IconId("bag"),IconCategory("Themify Icons")]
		Bag = 0xe655,
		///<summary>Move</summary>
		[Description("Move"),IconId("move"),IconCategory("Themify Icons")]
		Move = 0xe656,
		///<summary>ArrowsVertical</summary>
		[Description("ArrowsVertical"),IconId("arrows-vertical"),IconCategory("Themify Icons")]
		ArrowsVertical = 0xe657,
		///<summary>ArrowsHorizontal</summary>
		[Description("ArrowsHorizontal"),IconId("arrows-horizontal"),IconCategory("Themify Icons")]
		ArrowsHorizontal = 0xe658,
		///<summary>Fullscreen</summary>
		[Description("Fullscreen"),IconId("fullscreen"),IconCategory("Themify Icons")]
		Fullscreen = 0xe659,
		///<summary>ArrowTopRight</summary>
		[Description("ArrowTopRight"),IconId("arrow-top-right"),IconCategory("Themify Icons")]
		ArrowTopRight = 0xe65a,
		///<summary>ArrowTopLeft</summary>
		[Description("ArrowTopLeft"),IconId("arrow-top-left"),IconCategory("Themify Icons")]
		ArrowTopLeft = 0xe65b,
		///<summary>ArrowCircleUp</summary>
		[Description("ArrowCircleUp"),IconId("arrow-circle-up"),IconCategory("Themify Icons")]
		ArrowCircleUp = 0xe65c,
		///<summary>ArrowCircleRight</summary>
		[Description("ArrowCircleRight"),IconId("arrow-circle-right"),IconCategory("Themify Icons")]
		ArrowCircleRight = 0xe65d,
		///<summary>ArrowCircleLeft</summary>
		[Description("ArrowCircleLeft"),IconId("arrow-circle-left"),IconCategory("Themify Icons")]
		ArrowCircleLeft = 0xe65e,
		///<summary>ArrowCircleDown</summary>
		[Description("ArrowCircleDown"),IconId("arrow-circle-down"),IconCategory("Themify Icons")]
		ArrowCircleDown = 0xe65f,
		///<summary>AngleDoubleUp</summary>
		[Description("AngleDoubleUp"),IconId("angle-double-up"),IconCategory("Themify Icons")]
		AngleDoubleUp = 0xe660,
		///<summary>AngleDoubleRight</summary>
		[Description("AngleDoubleRight"),IconId("angle-double-right"),IconCategory("Themify Icons")]
		AngleDoubleRight = 0xe661,
		///<summary>AngleDoubleLeft</summary>
		[Description("AngleDoubleLeft"),IconId("angle-double-left"),IconCategory("Themify Icons")]
		AngleDoubleLeft = 0xe662,
		///<summary>AngleDoubleDown</summary>
		[Description("AngleDoubleDown"),IconId("angle-double-down"),IconCategory("Themify Icons")]
		AngleDoubleDown = 0xe663,
		///<summary>Zip</summary>
		[Description("Zip"),IconId("zip"),IconCategory("Themify Icons")]
		Zip = 0xe664,
		///<summary>World</summary>
		[Description("World"),IconId("world"),IconCategory("Themify Icons")]
		World = 0xe665,
		///<summary>Wheelchair</summary>
		[Description("Wheelchair"),IconId("wheelchair"),IconCategory("Themify Icons")]
		Wheelchair = 0xe666,
		///<summary>ViewList</summary>
		[Description("ViewList"),IconId("view-list"),IconCategory("Themify Icons")]
		ViewList = 0xe667,
		///<summary>ViewListAlt</summary>
		[Description("ViewListAlt"),IconId("view-list-alt"),IconCategory("Themify Icons")]
		ViewListAlt = 0xe668,
		///<summary>ViewGrid</summary>
		[Description("ViewGrid"),IconId("view-grid"),IconCategory("Themify Icons")]
		ViewGrid = 0xe669,
		///<summary>Uppercase</summary>
		[Description("Uppercase"),IconId("uppercase"),IconCategory("Themify Icons")]
		Uppercase = 0xe66a,
		///<summary>Upload</summary>
		[Description("Upload"),IconId("upload"),IconCategory("Themify Icons")]
		Upload = 0xe66b,
		///<summary>Underline</summary>
		[Description("Underline"),IconId("underline"),IconCategory("Themify Icons")]
		Underline = 0xe66c,
		///<summary>Truck</summary>
		[Description("Truck"),IconId("truck"),IconCategory("Themify Icons")]
		Truck = 0xe66d,
		///<summary>Timer</summary>
		[Description("Timer"),IconId("timer"),IconCategory("Themify Icons")]
		Timer = 0xe66e,
		///<summary>Ticket</summary>
		[Description("Ticket"),IconId("ticket"),IconCategory("Themify Icons")]
		Ticket = 0xe66f,
		///<summary>ThumbUp</summary>
		[Description("ThumbUp"),IconId("thumb-up"),IconCategory("Themify Icons")]
		ThumbUp = 0xe670,
		///<summary>ThumbDown</summary>
		[Description("ThumbDown"),IconId("thumb-down"),IconCategory("Themify Icons")]
		ThumbDown = 0xe671,
		///<summary>Text</summary>
		[Description("Text"),IconId("text"),IconCategory("Themify Icons")]
		Text = 0xe672,
		///<summary>StatsUp</summary>
		[Description("StatsUp"),IconId("stats-up"),IconCategory("Themify Icons")]
		StatsUp = 0xe673,
		///<summary>StatsDown</summary>
		[Description("StatsDown"),IconId("stats-down"),IconCategory("Themify Icons")]
		StatsDown = 0xe674,
		///<summary>SplitV</summary>
		[Description("SplitV"),IconId("split-v"),IconCategory("Themify Icons")]
		SplitV = 0xe675,
		///<summary>SplitH</summary>
		[Description("SplitH"),IconId("split-h"),IconCategory("Themify Icons")]
		SplitH = 0xe676,
		///<summary>Smallcap</summary>
		[Description("Smallcap"),IconId("smallcap"),IconCategory("Themify Icons")]
		Smallcap = 0xe677,
		///<summary>Shine</summary>
		[Description("Shine"),IconId("shine"),IconCategory("Themify Icons")]
		Shine = 0xe678,
		///<summary>ShiftRight</summary>
		[Description("ShiftRight"),IconId("shift-right"),IconCategory("Themify Icons")]
		ShiftRight = 0xe679,
		///<summary>ShiftLeft</summary>
		[Description("ShiftLeft"),IconId("shift-left"),IconCategory("Themify Icons")]
		ShiftLeft = 0xe67a,
		///<summary>Shield</summary>
		[Description("Shield"),IconId("shield"),IconCategory("Themify Icons")]
		Shield = 0xe67b,
		///<summary>Notepad</summary>
		[Description("Notepad"),IconId("notepad"),IconCategory("Themify Icons")]
		Notepad = 0xe67c,
		///<summary>Server</summary>
		[Description("Server"),IconId("server"),IconCategory("Themify Icons")]
		Server = 0xe67d,
		///<summary>QuoteRight</summary>
		[Description("QuoteRight"),IconId("quote-right"),IconCategory("Themify Icons")]
		QuoteRight = 0xe67e,
		///<summary>QuoteLeft</summary>
		[Description("QuoteLeft"),IconId("quote-left"),IconCategory("Themify Icons")]
		QuoteLeft = 0xe67f,
		///<summary>Pulse</summary>
		[Description("Pulse"),IconId("pulse"),IconCategory("Themify Icons")]
		Pulse = 0xe680,
		///<summary>Printer</summary>
		[Description("Printer"),IconId("printer"),IconCategory("Themify Icons")]
		Printer = 0xe681,
		///<summary>PowerOff</summary>
		[Description("PowerOff"),IconId("power-off"),IconCategory("Themify Icons")]
		PowerOff = 0xe682,
		///<summary>Plug</summary>
		[Description("Plug"),IconId("plug"),IconCategory("Themify Icons")]
		Plug = 0xe683,
		///<summary>PieChart</summary>
		[Description("PieChart"),IconId("pie-chart"),IconCategory("Themify Icons")]
		PieChart = 0xe684,
		///<summary>Paragraph</summary>
		[Description("Paragraph"),IconId("paragraph"),IconCategory("Themify Icons")]
		Paragraph = 0xe685,
		///<summary>Panel</summary>
		[Description("Panel"),IconId("panel"),IconCategory("Themify Icons")]
		Panel = 0xe686,
		///<summary>Package</summary>
		[Description("Package"),IconId("package"),IconCategory("Themify Icons")]
		Package = 0xe687,
		///<summary>Music</summary>
		[Description("Music"),IconId("music"),IconCategory("Themify Icons")]
		Music = 0xe688,
		///<summary>MusicAlt</summary>
		[Description("MusicAlt"),IconId("music-alt"),IconCategory("Themify Icons")]
		MusicAlt = 0xe689,
		///<summary>Mouse</summary>
		[Description("Mouse"),IconId("mouse"),IconCategory("Themify Icons")]
		Mouse = 0xe68a,
		///<summary>MouseAlt</summary>
		[Description("MouseAlt"),IconId("mouse-alt"),IconCategory("Themify Icons")]
		MouseAlt = 0xe68b,
		///<summary>Money</summary>
		[Description("Money"),IconId("money"),IconCategory("Themify Icons")]
		Money = 0xe68c,
		///<summary>Microphone</summary>
		[Description("Microphone"),IconId("microphone"),IconCategory("Themify Icons")]
		Microphone = 0xe68d,
		///<summary>Menu</summary>
		[Description("Menu"),IconId("menu"),IconCategory("Themify Icons")]
		Menu = 0xe68e,
		///<summary>MenuAlt</summary>
		[Description("MenuAlt"),IconId("menu-alt"),IconCategory("Themify Icons")]
		MenuAlt = 0xe68f,
		///<summary>Map</summary>
		[Description("Map"),IconId("map"),IconCategory("Themify Icons")]
		Map = 0xe690,
		///<summary>MapAlt</summary>
		[Description("MapAlt"),IconId("map-alt"),IconCategory("Themify Icons")]
		MapAlt = 0xe691,
		///<summary>Loop</summary>
		[Description("Loop"),IconId("loop"),IconCategory("Themify Icons")]
		Loop = 0xe692,
		///<summary>LocationPin</summary>
		[Description("LocationPin"),IconId("location-pin"),IconCategory("Themify Icons")]
		LocationPin = 0xe693,
		///<summary>List</summary>
		[Description("List"),IconId("list"),IconCategory("Themify Icons")]
		List = 0xe694,
		///<summary>LightBulb</summary>
		[Description("LightBulb"),IconId("light-bulb"),IconCategory("Themify Icons")]
		LightBulb = 0xe695,
		///<summary>Italic</summary>
		[Description("Italic"),IconId("Italic"),IconCategory("Themify Icons")]
		Italic = 0xe696,
		///<summary>Info</summary>
		[Description("Info"),IconId("info"),IconCategory("Themify Icons")]
		Info = 0xe697,
		///<summary>Infinite</summary>
		[Description("Infinite"),IconId("infinite"),IconCategory("Themify Icons")]
		Infinite = 0xe698,
		///<summary>IdBadge</summary>
		[Description("IdBadge"),IconId("id-badge"),IconCategory("Themify Icons")]
		IdBadge = 0xe699,
		///<summary>Hummer</summary>
		[Description("Hummer"),IconId("hummer"),IconCategory("Themify Icons")]
		Hummer = 0xe69a,
		///<summary>Home</summary>
		[Description("Home"),IconId("home"),IconCategory("Themify Icons")]
		Home = 0xe69b,
		///<summary>Help</summary>
		[Description("Help"),IconId("help"),IconCategory("Themify Icons")]
		Help = 0xe69c,
		///<summary>Headphone</summary>
		[Description("Headphone"),IconId("headphone"),IconCategory("Themify Icons")]
		Headphone = 0xe69d,
		///<summary>Harddrives</summary>
		[Description("Harddrives"),IconId("harddrives"),IconCategory("Themify Icons")]
		Harddrives = 0xe69e,
		///<summary>Harddrive</summary>
		[Description("Harddrive"),IconId("harddrive"),IconCategory("Themify Icons")]
		Harddrive = 0xe69f,
		///<summary>Gift</summary>
		[Description("Gift"),IconId("gift"),IconCategory("Themify Icons")]
		Gift = 0xe6a0,
		///<summary>Game</summary>
		[Description("Game"),IconId("game"),IconCategory("Themify Icons")]
		Game = 0xe6a1,
		///<summary>Filter</summary>
		[Description("Filter"),IconId("filter"),IconCategory("Themify Icons")]
		Filter = 0xe6a2,
		///<summary>Files</summary>
		[Description("Files"),IconId("files"),IconCategory("Themify Icons")]
		Files = 0xe6a3,
		///<summary>File</summary>
		[Description("File"),IconId("file"),IconCategory("Themify Icons")]
		File = 0xe6a4,
		///<summary>Eraser</summary>
		[Description("Eraser"),IconId("eraser"),IconCategory("Themify Icons")]
		Eraser = 0xe6a5,
		///<summary>Envelope</summary>
		[Description("Envelope"),IconId("envelope"),IconCategory("Themify Icons")]
		Envelope = 0xe6a6,
		///<summary>Download</summary>
		[Description("Download"),IconId("download"),IconCategory("Themify Icons")]
		Download = 0xe6a7,
		///<summary>Direction</summary>
		[Description("Direction"),IconId("direction"),IconCategory("Themify Icons")]
		Direction = 0xe6a8,
		///<summary>DirectionAlt</summary>
		[Description("DirectionAlt"),IconId("direction-alt"),IconCategory("Themify Icons")]
		DirectionAlt = 0xe6a9,
		///<summary>Dashboard</summary>
		[Description("Dashboard"),IconId("dashboard"),IconCategory("Themify Icons")]
		Dashboard = 0xe6aa,
		///<summary>ControlStop</summary>
		[Description("ControlStop"),IconId("control-stop"),IconCategory("Themify Icons")]
		ControlStop = 0xe6ab,
		///<summary>ControlShuffle</summary>
		[Description("ControlShuffle"),IconId("control-shuffle"),IconCategory("Themify Icons")]
		ControlShuffle = 0xe6ac,
		///<summary>ControlPlay</summary>
		[Description("ControlPlay"),IconId("control-play"),IconCategory("Themify Icons")]
		ControlPlay = 0xe6ad,
		///<summary>ControlPause</summary>
		[Description("ControlPause"),IconId("control-pause"),IconCategory("Themify Icons")]
		ControlPause = 0xe6ae,
		///<summary>ControlForward</summary>
		[Description("ControlForward"),IconId("control-forward"),IconCategory("Themify Icons")]
		ControlForward = 0xe6af,
		///<summary>ControlBackward</summary>
		[Description("ControlBackward"),IconId("control-backward"),IconCategory("Themify Icons")]
		ControlBackward = 0xe6b0,
		///<summary>Cloud</summary>
		[Description("Cloud"),IconId("cloud"),IconCategory("Themify Icons")]
		Cloud = 0xe6b1,
		///<summary>CloudUp</summary>
		[Description("CloudUp"),IconId("cloud-up"),IconCategory("Themify Icons")]
		CloudUp = 0xe6b2,
		///<summary>CloudDown</summary>
		[Description("CloudDown"),IconId("cloud-down"),IconCategory("Themify Icons")]
		CloudDown = 0xe6b3,
		///<summary>Clipboard</summary>
		[Description("Clipboard"),IconId("clipboard"),IconCategory("Themify Icons")]
		Clipboard = 0xe6b4,
		///<summary>Car</summary>
		[Description("Car"),IconId("car"),IconCategory("Themify Icons")]
		Car = 0xe6b5,
		///<summary>Calendar</summary>
		[Description("Calendar"),IconId("calendar"),IconCategory("Themify Icons")]
		Calendar = 0xe6b6,
		///<summary>Book</summary>
		[Description("Book"),IconId("book"),IconCategory("Themify Icons")]
		Book = 0xe6b7,
		///<summary>Bell</summary>
		[Description("Bell"),IconId("bell"),IconCategory("Themify Icons")]
		Bell = 0xe6b8,
		///<summary>Basketball</summary>
		[Description("Basketball"),IconId("basketball"),IconCategory("Themify Icons")]
		Basketball = 0xe6b9,
		///<summary>BarChart</summary>
		[Description("BarChart"),IconId("bar-chart"),IconCategory("Themify Icons")]
		BarChart = 0xe6ba,
		///<summary>BarChartAlt</summary>
		[Description("BarChartAlt"),IconId("bar-chart-alt"),IconCategory("Themify Icons")]
		BarChartAlt = 0xe6bb,
		///<summary>BackRight</summary>
		[Description("BackRight"),IconId("back-right"),IconCategory("Themify Icons")]
		BackRight = 0xe6bc,
		///<summary>BackLeft</summary>
		[Description("BackLeft"),IconId("back-left"),IconCategory("Themify Icons")]
		BackLeft = 0xe6bd,
		///<summary>ArrowsCorner</summary>
		[Description("ArrowsCorner"),IconId("arrows-corner"),IconCategory("Themify Icons")]
		ArrowsCorner = 0xe6be,
		///<summary>Archive</summary>
		[Description("Archive"),IconId("archive"),IconCategory("Themify Icons")]
		Archive = 0xe6bf,
		///<summary>Anchor</summary>
		[Description("Anchor"),IconId("anchor"),IconCategory("Themify Icons")]
		Anchor = 0xe6c0,
		///<summary>AlignRight</summary>
		[Description("AlignRight"),IconId("align-right"),IconCategory("Themify Icons")]
		AlignRight = 0xe6c1,
		///<summary>AlignLeft</summary>
		[Description("AlignLeft"),IconId("align-left"),IconCategory("Themify Icons")]
		AlignLeft = 0xe6c2,
		///<summary>AlignJustify</summary>
		[Description("AlignJustify"),IconId("align-justify"),IconCategory("Themify Icons")]
		AlignJustify = 0xe6c3,
		///<summary>AlignCenter</summary>
		[Description("AlignCenter"),IconId("align-center"),IconCategory("Themify Icons")]
		AlignCenter = 0xe6c4,
		///<summary>Alert</summary>
		[Description("Alert"),IconId("alert"),IconCategory("Themify Icons")]
		Alert = 0xe6c5,
		///<summary>AlarmClock</summary>
		[Description("AlarmClock"),IconId("alarm-clock"),IconCategory("Themify Icons")]
		AlarmClock = 0xe6c6,
		///<summary>Agenda</summary>
		[Description("Agenda"),IconId("agenda"),IconCategory("Themify Icons")]
		Agenda = 0xe6c7,
		///<summary>Write</summary>
		[Description("Write"),IconId("write"),IconCategory("Themify Icons")]
		Write = 0xe6c8,
		///<summary>Window</summary>
		[Description("Window"),IconId("window"),IconCategory("Themify Icons")]
		Window = 0xe6c9,
		///<summary>Widgetized</summary>
		[Description("Widgetized"),IconId("widgetized"),IconCategory("Themify Icons")]
		Widgetized = 0xe6ca,
		///<summary>Widget</summary>
		[Description("Widget"),IconId("widget"),IconCategory("Themify Icons")]
		Widget = 0xe6cb,
		///<summary>WidgetAlt</summary>
		[Description("WidgetAlt"),IconId("widget-alt"),IconCategory("Themify Icons")]
		WidgetAlt = 0xe6cc,
		///<summary>Wallet</summary>
		[Description("Wallet"),IconId("wallet"),IconCategory("Themify Icons")]
		Wallet = 0xe6cd,
		///<summary>VideoClapper</summary>
		[Description("VideoClapper"),IconId("video-clapper"),IconCategory("Themify Icons")]
		VideoClapper = 0xe6ce,
		///<summary>VideoCamera</summary>
		[Description("VideoCamera"),IconId("video-camera"),IconCategory("Themify Icons")]
		VideoCamera = 0xe6cf,
		///<summary>Vector</summary>
		[Description("Vector"),IconId("vector"),IconCategory("Themify Icons")]
		Vector = 0xe6d0,
		///<summary>ThemifyLogo</summary>
		[Description("ThemifyLogo"),IconId("themify-logo"),IconCategory("Themify Icons")]
		ThemifyLogo = 0xe6d1,
		///<summary>ThemifyFavicon</summary>
		[Description("ThemifyFavicon"),IconId("themify-favicon"),IconCategory("Themify Icons")]
		ThemifyFavicon = 0xe6d2,
		///<summary>ThemifyFaviconAlt</summary>
		[Description("ThemifyFaviconAlt"),IconId("themify-favicon-alt"),IconCategory("Themify Icons")]
		ThemifyFaviconAlt = 0xe6d3,
		///<summary>Support</summary>
		[Description("Support"),IconId("support"),IconCategory("Themify Icons")]
		Support = 0xe6d4,
		///<summary>Stamp</summary>
		[Description("Stamp"),IconId("stamp"),IconCategory("Themify Icons")]
		Stamp = 0xe6d5,
		///<summary>SplitVAlt</summary>
		[Description("SplitVAlt"),IconId("split-v-alt"),IconCategory("Themify Icons")]
		SplitVAlt = 0xe6d6,
		///<summary>Slice</summary>
		[Description("Slice"),IconId("slice"),IconCategory("Themify Icons")]
		Slice = 0xe6d7,
		///<summary>Shortcode</summary>
		[Description("Shortcode"),IconId("shortcode"),IconCategory("Themify Icons")]
		Shortcode = 0xe6d8,
		///<summary>ShiftRightAlt</summary>
		[Description("ShiftRightAlt"),IconId("shift-right-alt"),IconCategory("Themify Icons")]
		ShiftRightAlt = 0xe6d9,
		///<summary>ShiftLeftAlt</summary>
		[Description("ShiftLeftAlt"),IconId("shift-left-alt"),IconCategory("Themify Icons")]
		ShiftLeftAlt = 0xe6da,
		///<summary>RulerAlt2</summary>
		[Description("RulerAlt2"),IconId("ruler-alt-2"),IconCategory("Themify Icons")]
		RulerAlt2 = 0xe6db,
		///<summary>Receipt</summary>
		[Description("Receipt"),IconId("receipt"),IconCategory("Themify Icons")]
		Receipt = 0xe6dc,
		///<summary>Pin2</summary>
		[Description("Pin2"),IconId("pin2"),IconCategory("Themify Icons")]
		Pin2 = 0xe6dd,
		///<summary>PinAlt</summary>
		[Description("PinAlt"),IconId("pin-alt"),IconCategory("Themify Icons")]
		PinAlt = 0xe6de,
		///<summary>PencilAlt2</summary>
		[Description("PencilAlt2"),IconId("pencil-alt2"),IconCategory("Themify Icons")]
		PencilAlt2 = 0xe6df,
		///<summary>Palette</summary>
		[Description("Palette"),IconId("palette"),IconCategory("Themify Icons")]
		Palette = 0xe6e0,
		///<summary>More</summary>
		[Description("More"),IconId("more"),IconCategory("Themify Icons")]
		More = 0xe6e1,
		///<summary>MoreAlt</summary>
		[Description("MoreAlt"),IconId("more-alt"),IconCategory("Themify Icons")]
		MoreAlt = 0xe6e2,
		///<summary>MicrophoneAlt</summary>
		[Description("MicrophoneAlt"),IconId("microphone-alt"),IconCategory("Themify Icons")]
		MicrophoneAlt = 0xe6e3,
		///<summary>Magnet</summary>
		[Description("Magnet"),IconId("magnet"),IconCategory("Themify Icons")]
		Magnet = 0xe6e4,
		///<summary>LineDouble</summary>
		[Description("LineDouble"),IconId("line-double"),IconCategory("Themify Icons")]
		LineDouble = 0xe6e5,
		///<summary>LineDotted</summary>
		[Description("LineDotted"),IconId("line-dotted"),IconCategory("Themify Icons")]
		LineDotted = 0xe6e6,
		///<summary>LineDashed</summary>
		[Description("LineDashed"),IconId("line-dashed"),IconCategory("Themify Icons")]
		LineDashed = 0xe6e7,
		///<summary>LayoutWidthFull</summary>
		[Description("LayoutWidthFull"),IconId("layout-width-full"),IconCategory("Themify Icons")]
		LayoutWidthFull = 0xe6e8,
		///<summary>LayoutWidthDefault</summary>
		[Description("LayoutWidthDefault"),IconId("layout-width-default"),IconCategory("Themify Icons")]
		LayoutWidthDefault = 0xe6e9,
		///<summary>LayoutWidthDefaultAlt</summary>
		[Description("LayoutWidthDefaultAlt"),IconId("layout-width-default-alt"),IconCategory("Themify Icons")]
		LayoutWidthDefaultAlt = 0xe6ea,
		///<summary>LayoutTab</summary>
		[Description("LayoutTab"),IconId("layout-tab"),IconCategory("Themify Icons")]
		LayoutTab = 0xe6eb,
		///<summary>LayoutTabWindow</summary>
		[Description("LayoutTabWindow"),IconId("layout-tab-window"),IconCategory("Themify Icons")]
		LayoutTabWindow = 0xe6ec,
		///<summary>LayoutTabV</summary>
		[Description("LayoutTabV"),IconId("layout-tab-v"),IconCategory("Themify Icons")]
		LayoutTabV = 0xe6ed,
		///<summary>LayoutTabMin</summary>
		[Description("LayoutTabMin"),IconId("layout-tab-min"),IconCategory("Themify Icons")]
		LayoutTabMin = 0xe6ee,
		///<summary>LayoutSlider</summary>
		[Description("LayoutSlider"),IconId("layout-slider"),IconCategory("Themify Icons")]
		LayoutSlider = 0xe6ef,
		///<summary>LayoutSliderAlt</summary>
		[Description("LayoutSliderAlt"),IconId("layout-slider-alt"),IconCategory("Themify Icons")]
		LayoutSliderAlt = 0xe6f0,
		///<summary>LayoutSidebarRight</summary>
		[Description("LayoutSidebarRight"),IconId("layout-sidebar-right"),IconCategory("Themify Icons")]
		LayoutSidebarRight = 0xe6f1,
		///<summary>LayoutSidebarNone</summary>
		[Description("LayoutSidebarNone"),IconId("layout-sidebar-none"),IconCategory("Themify Icons")]
		LayoutSidebarNone = 0xe6f2,
		///<summary>LayoutSidebarLeft</summary>
		[Description("LayoutSidebarLeft"),IconId("layout-sidebar-left"),IconCategory("Themify Icons")]
		LayoutSidebarLeft = 0xe6f3,
		///<summary>LayoutPlaceholder</summary>
		[Description("LayoutPlaceholder"),IconId("layout-placeholder"),IconCategory("Themify Icons")]
		LayoutPlaceholder = 0xe6f4,
		///<summary>LayoutMenu</summary>
		[Description("LayoutMenu"),IconId("layout-menu"),IconCategory("Themify Icons")]
		LayoutMenu = 0xe6f5,
		///<summary>LayoutMenuV</summary>
		[Description("LayoutMenuV"),IconId("layout-menu-v"),IconCategory("Themify Icons")]
		LayoutMenuV = 0xe6f6,
		///<summary>LayoutMenuSeparated</summary>
		[Description("LayoutMenuSeparated"),IconId("layout-menu-separated"),IconCategory("Themify Icons")]
		LayoutMenuSeparated = 0xe6f7,
		///<summary>LayoutMenuFull</summary>
		[Description("LayoutMenuFull"),IconId("layout-menu-full"),IconCategory("Themify Icons")]
		LayoutMenuFull = 0xe6f8,
		///<summary>LayoutMediaRightAlt</summary>
		[Description("LayoutMediaRightAlt"),IconId("layout-media-right-alt"),IconCategory("Themify Icons")]
		LayoutMediaRightAlt = 0xe6f9,
		///<summary>LayoutMediaRight</summary>
		[Description("LayoutMediaRight"),IconId("layout-media-right"),IconCategory("Themify Icons")]
		LayoutMediaRight = 0xe6fa,
		///<summary>LayoutMediaOverlay</summary>
		[Description("LayoutMediaOverlay"),IconId("layout-media-overlay"),IconCategory("Themify Icons")]
		LayoutMediaOverlay = 0xe6fb,
		///<summary>LayoutMediaOverlayAlt</summary>
		[Description("LayoutMediaOverlayAlt"),IconId("layout-media-overlay-alt"),IconCategory("Themify Icons")]
		LayoutMediaOverlayAlt = 0xe6fc,
		///<summary>LayoutMediaOverlayAlt2</summary>
		[Description("LayoutMediaOverlayAlt2"),IconId("layout-media-overlay-alt-2"),IconCategory("Themify Icons")]
		LayoutMediaOverlayAlt2 = 0xe6fd,
		///<summary>LayoutMediaLeftAlt</summary>
		[Description("LayoutMediaLeftAlt"),IconId("layout-media-left-alt"),IconCategory("Themify Icons")]
		LayoutMediaLeftAlt = 0xe6fe,
		///<summary>LayoutMediaLeft</summary>
		[Description("LayoutMediaLeft"),IconId("layout-media-left"),IconCategory("Themify Icons")]
		LayoutMediaLeft = 0xe6ff,
		///<summary>LayoutMediaCenterAlt</summary>
		[Description("LayoutMediaCenterAlt"),IconId("layout-media-center-alt"),IconCategory("Themify Icons")]
		LayoutMediaCenterAlt = 0xe700,
		///<summary>LayoutMediaCenter</summary>
		[Description("LayoutMediaCenter"),IconId("layout-media-center"),IconCategory("Themify Icons")]
		LayoutMediaCenter = 0xe701,
		///<summary>LayoutListThumb</summary>
		[Description("LayoutListThumb"),IconId("layout-list-thumb"),IconCategory("Themify Icons")]
		LayoutListThumb = 0xe702,
		///<summary>LayoutListThumbAlt</summary>
		[Description("LayoutListThumbAlt"),IconId("layout-list-thumb-alt"),IconCategory("Themify Icons")]
		LayoutListThumbAlt = 0xe703,
		///<summary>LayoutListPost</summary>
		[Description("LayoutListPost"),IconId("layout-list-post"),IconCategory("Themify Icons")]
		LayoutListPost = 0xe704,
		///<summary>LayoutListLargeImage</summary>
		[Description("LayoutListLargeImage"),IconId("layout-list-large-image"),IconCategory("Themify Icons")]
		LayoutListLargeImage = 0xe705,
		///<summary>LayoutLineSolid</summary>
		[Description("LayoutLineSolid"),IconId("layout-line-solid"),IconCategory("Themify Icons")]
		LayoutLineSolid = 0xe706,
		///<summary>LayoutGrid4</summary>
		[Description("LayoutGrid4"),IconId("layout-grid4"),IconCategory("Themify Icons")]
		LayoutGrid4 = 0xe707,
		///<summary>LayoutGrid3</summary>
		[Description("LayoutGrid3"),IconId("layout-grid3"),IconCategory("Themify Icons")]
		LayoutGrid3 = 0xe708,
		///<summary>LayoutGrid2</summary>
		[Description("LayoutGrid2"),IconId("layout-grid2"),IconCategory("Themify Icons")]
		LayoutGrid2 = 0xe709,
		///<summary>LayoutGrid2Thumb</summary>
		[Description("LayoutGrid2Thumb"),IconId("layout-grid2-thumb"),IconCategory("Themify Icons")]
		LayoutGrid2Thumb = 0xe70a,
		///<summary>LayoutCtaRight</summary>
		[Description("LayoutCtaRight"),IconId("layout-cta-right"),IconCategory("Themify Icons")]
		LayoutCtaRight = 0xe70b,
		///<summary>LayoutCtaLeft</summary>
		[Description("LayoutCtaLeft"),IconId("layout-cta-left"),IconCategory("Themify Icons")]
		LayoutCtaLeft = 0xe70c,
		///<summary>LayoutCtaCenter</summary>
		[Description("LayoutCtaCenter"),IconId("layout-cta-center"),IconCategory("Themify Icons")]
		LayoutCtaCenter = 0xe70d,
		///<summary>LayoutCtaBtnRight</summary>
		[Description("LayoutCtaBtnRight"),IconId("layout-cta-btn-right"),IconCategory("Themify Icons")]
		LayoutCtaBtnRight = 0xe70e,
		///<summary>LayoutCtaBtnLeft</summary>
		[Description("LayoutCtaBtnLeft"),IconId("layout-cta-btn-left"),IconCategory("Themify Icons")]
		LayoutCtaBtnLeft = 0xe70f,
		///<summary>LayoutColumn4</summary>
		[Description("LayoutColumn4"),IconId("layout-column4"),IconCategory("Themify Icons")]
		LayoutColumn4 = 0xe710,
		///<summary>LayoutColumn3</summary>
		[Description("LayoutColumn3"),IconId("layout-column3"),IconCategory("Themify Icons")]
		LayoutColumn3 = 0xe711,
		///<summary>LayoutColumn2</summary>
		[Description("LayoutColumn2"),IconId("layout-column2"),IconCategory("Themify Icons")]
		LayoutColumn2 = 0xe712,
		///<summary>LayoutAccordionSeparated</summary>
		[Description("LayoutAccordionSeparated"),IconId("layout-accordion-separated"),IconCategory("Themify Icons")]
		LayoutAccordionSeparated = 0xe713,
		///<summary>LayoutAccordionMerged</summary>
		[Description("LayoutAccordionMerged"),IconId("layout-accordion-merged"),IconCategory("Themify Icons")]
		LayoutAccordionMerged = 0xe714,
		///<summary>LayoutAccordionList</summary>
		[Description("LayoutAccordionList"),IconId("layout-accordion-list"),IconCategory("Themify Icons")]
		LayoutAccordionList = 0xe715,
		///<summary>InkPen</summary>
		[Description("InkPen"),IconId("ink-pen"),IconCategory("Themify Icons")]
		InkPen = 0xe716,
		///<summary>InfoAlt</summary>
		[Description("InfoAlt"),IconId("info-alt"),IconCategory("Themify Icons")]
		InfoAlt = 0xe717,
		///<summary>HelpAlt</summary>
		[Description("HelpAlt"),IconId("help-alt"),IconCategory("Themify Icons")]
		HelpAlt = 0xe718,
		///<summary>HeadphoneAlt</summary>
		[Description("HeadphoneAlt"),IconId("headphone-alt"),IconCategory("Themify Icons")]
		HeadphoneAlt = 0xe719,
		///<summary>HandPointUp</summary>
		[Description("HandPointUp"),IconId("hand-point-up"),IconCategory("Themify Icons")]
		HandPointUp = 0xe71a,
		///<summary>HandPointRight</summary>
		[Description("HandPointRight"),IconId("hand-point-right"),IconCategory("Themify Icons")]
		HandPointRight = 0xe71b,
		///<summary>HandPointLeft</summary>
		[Description("HandPointLeft"),IconId("hand-point-left"),IconCategory("Themify Icons")]
		HandPointLeft = 0xe71c,
		///<summary>HandPointDown</summary>
		[Description("HandPointDown"),IconId("hand-point-down"),IconCategory("Themify Icons")]
		HandPointDown = 0xe71d,
		///<summary>Gallery</summary>
		[Description("Gallery"),IconId("gallery"),IconCategory("Themify Icons")]
		Gallery = 0xe71e,
		///<summary>FaceSmile</summary>
		[Description("FaceSmile"),IconId("face-smile"),IconCategory("Themify Icons")]
		FaceSmile = 0xe71f,
		///<summary>FaceSad</summary>
		[Description("FaceSad"),IconId("face-sad"),IconCategory("Themify Icons")]
		FaceSad = 0xe720,
		///<summary>CreditCard</summary>
		[Description("CreditCard"),IconId("credit-card"),IconCategory("Themify Icons")]
		CreditCard = 0xe721,
		///<summary>ControlSkipForward</summary>
		[Description("ControlSkipForward"),IconId("control-skip-forward"),IconCategory("Themify Icons")]
		ControlSkipForward = 0xe722,
		///<summary>ControlSkipBackward</summary>
		[Description("ControlSkipBackward"),IconId("control-skip-backward"),IconCategory("Themify Icons")]
		ControlSkipBackward = 0xe723,
		///<summary>ControlRecord</summary>
		[Description("ControlRecord"),IconId("control-record"),IconCategory("Themify Icons")]
		ControlRecord = 0xe724,
		///<summary>ControlEject</summary>
		[Description("ControlEject"),IconId("control-eject"),IconCategory("Themify Icons")]
		ControlEject = 0xe725,
		///<summary>CommentsSmiley</summary>
		[Description("CommentsSmiley"),IconId("comments-smiley"),IconCategory("Themify Icons")]
		CommentsSmiley = 0xe726,
		///<summary>BrushAlt</summary>
		[Description("BrushAlt"),IconId("brush-alt"),IconCategory("Themify Icons")]
		BrushAlt = 0xe727,
		///<summary>Youtube</summary>
		[Description("Youtube"),IconId("youtube"),IconCategory("Themify Icons")]
		Youtube = 0xe728,
		///<summary>Vimeo</summary>
		[Description("Vimeo"),IconId("vimeo"),IconCategory("Themify Icons")]
		Vimeo = 0xe729,
		///<summary>Twitter</summary>
		[Description("Twitter"),IconId("twitter"),IconCategory("Themify Icons")]
		Twitter = 0xe72a,
		///<summary>Time</summary>
		[Description("Time"),IconId("time"),IconCategory("Themify Icons")]
		Time = 0xe72b,
		///<summary>Tumblr</summary>
		[Description("Tumblr"),IconId("tumblr"),IconCategory("Themify Icons")]
		Tumblr = 0xe72c,
		///<summary>Skype</summary>
		[Description("Skype"),IconId("skype"),IconCategory("Themify Icons")]
		Skype = 0xe72d,
		///<summary>Share</summary>
		[Description("Share"),IconId("share"),IconCategory("Themify Icons")]
		Share = 0xe72e,
		///<summary>ShareAlt</summary>
		[Description("ShareAlt"),IconId("share-alt"),IconCategory("Themify Icons")]
		ShareAlt = 0xe72f,
		///<summary>Rocket</summary>
		[Description("Rocket"),IconId("rocket"),IconCategory("Themify Icons")]
		Rocket = 0xe730,
		///<summary>Pinterest</summary>
		[Description("Pinterest"),IconId("pinterest"),IconCategory("Themify Icons")]
		Pinterest = 0xe731,
		///<summary>NewWindow</summary>
		[Description("NewWindow"),IconId("new-window"),IconCategory("Themify Icons")]
		NewWindow = 0xe732,
		///<summary>Microsoft</summary>
		[Description("Microsoft"),IconId("microsoft"),IconCategory("Themify Icons")]
		Microsoft = 0xe733,
		///<summary>ListOl</summary>
		[Description("ListOl"),IconId("list-ol"),IconCategory("Themify Icons")]
		ListOl = 0xe734,
		///<summary>Linkedin</summary>
		[Description("Linkedin"),IconId("linkedin"),IconCategory("Themify Icons")]
		Linkedin = 0xe735,
		///<summary>LayoutSidebar2</summary>
		[Description("LayoutSidebar2"),IconId("layout-sidebar-2"),IconCategory("Themify Icons")]
		LayoutSidebar2 = 0xe736,
		///<summary>LayoutGrid4Alt</summary>
		[Description("LayoutGrid4Alt"),IconId("layout-grid4-alt"),IconCategory("Themify Icons")]
		LayoutGrid4Alt = 0xe737,
		///<summary>LayoutGrid3Alt</summary>
		[Description("LayoutGrid3Alt"),IconId("layout-grid3-alt"),IconCategory("Themify Icons")]
		LayoutGrid3Alt = 0xe738,
		///<summary>LayoutGrid2Alt</summary>
		[Description("LayoutGrid2Alt"),IconId("layout-grid2-alt"),IconCategory("Themify Icons")]
		LayoutGrid2Alt = 0xe739,
		///<summary>LayoutColumn4Alt</summary>
		[Description("LayoutColumn4Alt"),IconId("layout-column4-alt"),IconCategory("Themify Icons")]
		LayoutColumn4Alt = 0xe73a,
		///<summary>LayoutColumn3Alt</summary>
		[Description("LayoutColumn3Alt"),IconId("layout-column3-alt"),IconCategory("Themify Icons")]
		LayoutColumn3Alt = 0xe73b,
		///<summary>LayoutColumn2Alt</summary>
		[Description("LayoutColumn2Alt"),IconId("layout-column2-alt"),IconCategory("Themify Icons")]
		LayoutColumn2Alt = 0xe73c,
		///<summary>Instagram</summary>
		[Description("Instagram"),IconId("instagram"),IconCategory("Themify Icons")]
		Instagram = 0xe73d,
		///<summary>Google</summary>
		[Description("Google"),IconId("google"),IconCategory("Themify Icons")]
		Google = 0xe73e,
		///<summary>Github</summary>
		[Description("Github"),IconId("github"),IconCategory("Themify Icons")]
		Github = 0xe73f,
		///<summary>Flickr</summary>
		[Description("Flickr"),IconId("flickr"),IconCategory("Themify Icons")]
		Flickr = 0xe740,
		///<summary>Facebook</summary>
		[Description("Facebook"),IconId("facebook"),IconCategory("Themify Icons")]
		Facebook = 0xe741,
		///<summary>Dropbox</summary>
		[Description("Dropbox"),IconId("dropbox"),IconCategory("Themify Icons")]
		Dropbox = 0xe742,
		///<summary>Dribbble</summary>
		[Description("Dribbble"),IconId("dribbble"),IconCategory("Themify Icons")]
		Dribbble = 0xe743,
		///<summary>Apple</summary>
		[Description("Apple"),IconId("apple"),IconCategory("Themify Icons")]
		Apple = 0xe744,
		///<summary>Android</summary>
		[Description("Android"),IconId("android"),IconCategory("Themify Icons")]
		Android = 0xe745,
		///<summary>Save</summary>
		[Description("Save"),IconId("save"),IconCategory("Themify Icons")]
		Save = 0xe746,
		///<summary>SaveAlt</summary>
		[Description("SaveAlt"),IconId("save-alt"),IconCategory("Themify Icons")]
		SaveAlt = 0xe747,
		///<summary>Yahoo</summary>
		[Description("Yahoo"),IconId("yahoo"),IconCategory("Themify Icons")]
		Yahoo = 0xe748,
		///<summary>Wordpress</summary>
		[Description("Wordpress"),IconId("wordpress"),IconCategory("Themify Icons")]
		Wordpress = 0xe749,
		///<summary>VimeoAlt</summary>
		[Description("VimeoAlt"),IconId("vimeo-alt"),IconCategory("Themify Icons")]
		VimeoAlt = 0xe74a,
		///<summary>TwitterAlt</summary>
		[Description("TwitterAlt"),IconId("twitter-alt"),IconCategory("Themify Icons")]
		TwitterAlt = 0xe74b,
		///<summary>TumblrAlt</summary>
		[Description("TumblrAlt"),IconId("tumblr-alt"),IconCategory("Themify Icons")]
		TumblrAlt = 0xe74c,
		///<summary>Trello</summary>
		[Description("Trello"),IconId("trello"),IconCategory("Themify Icons")]
		Trello = 0xe74d,
		///<summary>StackOverflow</summary>
		[Description("StackOverflow"),IconId("stack-overflow"),IconCategory("Themify Icons")]
		StackOverflow = 0xe74e,
		///<summary>Soundcloud</summary>
		[Description("Soundcloud"),IconId("soundcloud"),IconCategory("Themify Icons")]
		Soundcloud = 0xe74f,
		///<summary>Sharethis</summary>
		[Description("Sharethis"),IconId("sharethis"),IconCategory("Themify Icons")]
		Sharethis = 0xe750,
		///<summary>SharethisAlt</summary>
		[Description("SharethisAlt"),IconId("sharethis-alt"),IconCategory("Themify Icons")]
		SharethisAlt = 0xe751,
		///<summary>Reddit</summary>
		[Description("Reddit"),IconId("reddit"),IconCategory("Themify Icons")]
		Reddit = 0xe752,
		///<summary>PinterestAlt</summary>
		[Description("PinterestAlt"),IconId("pinterest-alt"),IconCategory("Themify Icons")]
		PinterestAlt = 0xe753,
		///<summary>MicrosoftAlt</summary>
		[Description("MicrosoftAlt"),IconId("microsoft-alt"),IconCategory("Themify Icons")]
		MicrosoftAlt = 0xe754,
		///<summary>Linux</summary>
		[Description("Linux"),IconId("linux"),IconCategory("Themify Icons")]
		Linux = 0xe755,
		///<summary>Jsfiddle</summary>
		[Description("Jsfiddle"),IconId("jsfiddle"),IconCategory("Themify Icons")]
		Jsfiddle = 0xe756,
		///<summary>Joomla</summary>
		[Description("Joomla"),IconId("joomla"),IconCategory("Themify Icons")]
		Joomla = 0xe757,
		///<summary>Html5</summary>
		[Description("Html5"),IconId("html5"),IconCategory("Themify Icons")]
		Html5 = 0xe758,
		///<summary>FlickrAlt</summary>
		[Description("FlickrAlt"),IconId("flickr-alt"),IconCategory("Themify Icons")]
		FlickrAlt = 0xe759,
		///<summary>Email</summary>
		[Description("Email"),IconId("email"),IconCategory("Themify Icons")]
		Email = 0xe75a,
		///<summary>Drupal</summary>
		[Description("Drupal"),IconId("drupal"),IconCategory("Themify Icons")]
		Drupal = 0xe75b,
		///<summary>DropboxAlt</summary>
		[Description("DropboxAlt"),IconId("dropbox-alt"),IconCategory("Themify Icons")]
		DropboxAlt = 0xe75c,
		///<summary>Css3</summary>
		[Description("Css3"),IconId("css3"),IconCategory("Themify Icons")]
		Css3 = 0xe75d,
		///<summary>Rss</summary>
		[Description("Rss"),IconId("rss"),IconCategory("Themify Icons")]
		Rss = 0xe75e,
		///<summary>RssAlt</summary>
		[Description("RssAlt"),IconId("rss-alt"),IconCategory("Themify Icons")]
		RssAlt = 0xe75f,
	}
}
